name: My Action 1
on: [push, pull_request]
jobs:
  lint:
    name: My Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Script 1
        run: echo 1
      - name: Script 2
        run: |
          echo 2
          echo 3
