name: My Action 1
on: [push]
jobs:
  lint:
    name: My Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Custom action
        uses: ./
        id: my_action
        with:
          arg: 'hello'
